image: hashicorp/terraform:full

definitions:
  caches:
    awscli: aws

  steps:
    - step: &validate
        name: Validate code
        oidc: true
        caches:
          - awscli

        script:
          - . .bitbucket/setup-aws.sh

          - terraform init
          - terraform fmt
          - terraform validate
          - terraform plan

    - step: &infra
        name: Deploy infra
        condition:
          changesets:
            includePaths:
              - "bitbucket-pipelines.yml"
              - ".bitbucket/**"
              - "aws-sqs/**"
              - "aws-s3/**"
              - "main.tf"
              - "providers.tf"
        oidc: true
        caches:
          - awscli

        script:
          - . .bitbucket/setup-aws.sh

          - terraform apply -target=module.sqs
          - terraform apply -target=module.s3

    - step: &app
        name: Deploy app
        condition:
          changesets:
            includePaths:
              - "bitbucket-pipelines.yml"
              - ".bitbucket/**"
              - "nginx/**"
              - "main.tf"
              - "providers.tf"
        oidc: true
        caches:
          - awscli

        script:
          - . .bitbucket/setup-aws.sh

          - terraform apply -target=module.nginx

pipelines:
  default:
    - step: *validate
    - step: *infra
    - step: *app