apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.name }}-deployment"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/managed-by: {{ .Values.manager }}
    app.kubernetes.io/created-by: {{ .Values.author }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.image }}:{{ .Values.version }}"
        imagePullPolicy: Always
        env:
        - name: SQS_ENDPOINT
          value: {{ .Values.sqs }}
        - name: S3_ENDPOINT
          value: {{ .Values.s3 }}
        ports:
        - containerPort: {{ .Values.port }}
          protocol: TCP